In [ ]:
import pandas as pd

In [ ]:
# to get the path youu right click on the folder and copy path.assign it variable path.
#Then use pd.read_csv
#A csv file and excel are different in formating styles.
path = '/content/drive/MyDrive/TRAVEL _CITIES.csv'
cities= pd.read_csv(path)
cities
#.head is for reading the first five rows

                  City      Country  Population       Area
0                Solta      Croatia      1700.0       59.0
1           Greenville          USA     84554.0       68.0
2         Buenos Aires    Argentina  13591863.0     4758.0
3            Los Cabos       Mexico    287651.0     3750.0
4   Walla Walla Valley          USA     32237.0       33.0
5             Marakesh      Morocco    928850.0      200.0
6          Albuquerque   New Mexico    559277.0      491.0
7      Archipelago Sea      Finland     60000.0     8300.0
8         Iguazu Falls    Argentina         0.0      672.0
9        Salina Island        Italy      4000.0       27.0
10             Toronto       Canada       630.0  2731571.0
11         Pyeongchang  South Korea   2581000.0     3194.0
12                 NaN          NaN         NaN        NaN
13                 NaN          NaN         NaN        NaN
14                 NaN          NaN         NaN        NaN
15                 NaN          NaN         NaN        NaN
16                 NaN          NaN         NaN        NaN
17                 NaN          NaN         NaN        NaN
18                 NaN          NaN         NaN        NaN
19                 NaN          NaN         NaN        NaN
20                 NaN          NaN         NaN        NaN
21                 NaN          NaN         NaN        NaN
22                 NaN          NaN         NaN        NaN
23                 NaN          NaN         NaN        NaN
24                 NaN          NaN         NaN        NaN
25                 NaN          NaN         NaN        NaN
26                 NaN          NaN         NaN        NaN
27                 NaN          NaN         NaN        NaN
28                 NaN          NaN         NaN        NaN
29                 NaN          NaN         NaN        NaN

In [ ]:
cities= cities.dropna()
cities

                  City      Country  Population       Area
0                Solta      Croatia      1700.0       59.0
1           Greenville          USA     84554.0       68.0
2         Buenos Aires    Argentina  13591863.0     4758.0
3            Los Cabos       Mexico    287651.0     3750.0
4   Walla Walla Valley          USA     32237.0       33.0
5             Marakesh      Morocco    928850.0      200.0
6          Albuquerque   New Mexico    559277.0      491.0
7      Archipelago Sea      Finland     60000.0     8300.0
8         Iguazu Falls    Argentina         0.0      672.0
9        Salina Island        Italy      4000.0       27.0
10             Toronto       Canada       630.0  2731571.0
11         Pyeongchang  South Korea   2581000.0     3194.0

In [ ]:
cities_dict = cities.to_dict()
cities_dict

{'City': {0: 'Solta',
  1: 'Greenville',
  2: 'Buenos Aires',
  3: 'Los Cabos',
  4: 'Walla Walla Valley',
  5: 'Marakesh',
  6: 'Albuquerque',
  7: 'Archipelago Sea',
  8: 'Iguazu Falls',
  9: 'Salina Island',
  10: 'Toronto',
  11: 'Pyeongchang'},
 'Country': {0: 'Croatia',
  1: 'USA',
  2: 'Argentina',
  3: 'Mexico',
  4: 'USA',
  5: 'Morocco',
  6: 'New Mexico',
  7: 'Finland',
  8: 'Argentina',
  9: 'Italy',
  10: 'Canada',
  11: 'South Korea'},
 'Population': {0: 1700.0,
  1: 84554.0,
  2: 13591863.0,
  3: 287651.0,
  4: 32237.0,
  5: 928850.0,
  6: 559277.0,
  7: 60000.0,
  8: 0.0,
  9: 4000.0,
  10: 630.0,
  11: 2581000.0},
 'Area': {0: 59.0,
  1: 68.0,
  2: 4758.0,
  3: 3750.0,
  4: 33.0,
  5: 200.0,
  6: 491.0,
  7: 8300.0,
  8: 672.0,
  9: 27.0,
  10: 2731571.0,
  11: 3194.0}}

In [ ]:
salina = cities_dict[-3]

KeyError: -3

In [ ]:
import pandas as pd